// views/mediaView.js

const renderMediaView = (fileUrls) => {
    // Memastikan input adalah array, jika string tunggal maka ubah jadi array
    const urls = Array.isArray(fileUrls) ? fileUrls : [fileUrls];
    const isPdf = urls[0].toLowerCase().endsWith('.pdf');
    
    return `
    <!DOCTYPE html>
    <html lang="id">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Synectic Media View</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        <style>
            body { background: #0b141a; color: #e9edef; font-family: 'Segoe UI', sans-serif; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
            .card-custom { background: #1f2c33; border: 1px solid #2a3942; border-radius: 30px; box-shadow: 0 25px 50px rgba(0,0,0,0.8); width: 100%; max-width: 700px; overflow: hidden; }
            .media-header { padding: 20px; text-align: center; border-bottom: 1px solid #2a3942; }
            .media-header h5 { color: #00a884; font-weight: 800; letter-spacing: 2px; margin: 0; }
            .media-content { padding: 20px; text-align: center; }
            .media-frame { border-radius: 15px; border: 2px solid #00a884; box-shadow: 0 0 20px rgba(0,168,132,0.2); max-width: 100%; height: auto; max-height: 70vh; object-fit: contain; }
            .swiper { width: 100%; padding-bottom: 40px; }
            .swiper-button-next, .swiper-button-prev { color: #00a884 !important; }
            .swiper-pagination-bullet-active { background: #00a884 !important; }
            .btn-download { 
                background: #00a884; color: white; border: none; padding: 12px 30px; border-radius: 50px; 
                font-weight: 800; text-decoration: none; display: inline-flex; align-items: center; gap: 10px;
                transition: 0.3s; margin-top: 10px; box-shadow: 0 4px 15px rgba(0,168,132,0.4);
            }
            .btn-download:hover { background: #06cf9c; color: white; transform: scale(1.05); }
            .footer-tag { font-size: 0.75rem; color: #8696a0; text-align: center; padding: 15px; border-top: 1px solid #2a3942; }
            .zaki-name { color: #00a884; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="card-custom animate__animated animate__zoomIn">
            <div class="media-header">
                <h5>📁 ${isPdf ? 'LAMPIRAN DOKUMEN' : 'GALERI TUGAS'}</h5>
            </div>
            <div class="media-content">
                ${isPdf ? 
                    `<iframe src="${urls[0]}" width="100%" height="500px" class="media-frame"></iframe>` :
                    `<div class="swiper">
                        <div class="swiper-wrapper">
                            ${urls.map(url => `
                                <div class="swiper-slide">
                                    <img src="${url}" class="media-frame img-fluid" alt="Tugas">
                                </div>
                            `).join('')}
                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>`
                }
                <br>
                <a href="${urls[0]}" id="downloadLink" download class="btn-download">
                    <span>📥 DOWNLOAD FILE</span>
                </a>
            </div>
            <div class="footer-tag">
                LINK GENERATED BY <span class="zaki-name">SYNECTIC CORE</span>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
        <script>
            const swiper = new Swiper('.swiper', {
                pagination: { el: '.swiper-pagination', clickable: true },
                navigation: { nextEl: '.swiper-button-next', prevEl: '.swiper-button-prev' },
                on: {
                    slideChange: function () {
                        // Update link download agar sesuai dengan gambar yang sedang dilihat
                        const activeSlide = this.slides[this.activeIndex];
                        const img = activeSlide.querySelector('img');
                        if (img) {
                            document.getElementById('downloadLink').href = img.src;
                        }
                    }
                }
            });
        </script>
    </body>
    </html>`;
};

module.exports = { renderMediaView };
